workout/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :workouts
  root 'workouts#home'
  post '/workouts' => 'workouts#create', as: 'create_workout'
  get '/categories' =>'workouts#categories', as: 'categories'
  get '/workouts/category/:category' => 'workouts#category', as: 'category'
  patch '/workouts/:id' => 'workouts#update', as: 'patch_workout'
end

workout/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workout/app/models/exercise.rb
class Exercise < ApplicationRecord
end

workout/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

workout/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :find_workout, only: [:show, :edit, :update, :destroy]

    def home
    end

    def index
        @workout = Exercise.all
    end

    def show
    end

    def new
        @workout = Exercise.new
    end

    def create
        workout = Exercise.new(post_workout)
        if workout.save
            redirect_to workout_path(workout)
        else
            redirect_to new_workout_path
        end
    end

    def edit
    end

    def update
        if @workout.update(post_workout)
            redirect_to workout_path(@workout)
        else
            render 'edit'  
        end          
    end

    def destroy
        @workout.destroy
        redirect_to root_path
    end

    def category
        @workout = Exercise.where(category: (params[:category]))
    end

    def categories
        @categories = [
            "Warm Up",
            "Core Warm Up",
            "Support Progression",
            "Handstand Progression",
            "Pull-Up Progression",
            "Dipping Progression",
            "L-Sit Progression",
            "Squat Progression",
            "Push-Up Progression",
            "Row Progression"
        ]
    end

    private

    def post_workout
        params.require(:exercise).permit(:name, :category, :reps, :example, :progression)
    end

    def find_workout
        @workout = Exercise.find(params[:id])
    end


end

workout/app/helpers/application_helper.rb
module ApplicationHelper
end

workout/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

workout/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BWFA
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      = link_to "Home", root_path, :class => "navbar-brand" 
      %div.collapse.navbar-collapse#navbarNav
        %ul.navbar-nav
          %li.nav-item
            = link_to "Workouts", workouts_path, :class => "nav-link"
          %li.nav-item
            = link_to "Categories", categories_path, :class => "nav-link"
          %li.nav-item.disabled
            = link_to "Disabled", workouts_path, :class => "nav-link"

    = yield

workout/app/views/partials/_category.html.haml
%h2 This is the categories page...

- @workout.each do |i| 
    %category
        %h2= link_to "#{i.name}", workout_path(i.id)
        %h4= "#{i.category}"
        %h6= "Reps: #{i.reps}"
        %p= "#{i.progression}"
    %br

workout/app/views/partials/_edit_form.html.haml
= simple_form_for(@workout, url: patch_workout_path(@workout.id), html: {class: 'form-horizontal'}) do |f|
    = f.input :name, label: "Name", input_html: {class: "form-control"}
    = f.input :category, label: "Category", input_html: {class: "form-control"}
    = f.input :reps, label: "# of Reps", input_html: {class: "form-control"}
    = f.input :progression, label: "Progression Level", input_html: {class: "form-control"}
    = f.input :example, label: "YouTube Embed Link", input_html: {class: "form-control"}
    %br 
    = f.button :submit

workout/app/views/partials/_form.html.haml
= simple_form_for(@workout, url: create_workout_path, html: {class: 'form-horizontal'}) do |f|
    = f.input :name, label: "Name", input_html: {class: "form-control"}
    = f.input :category, label: "Category", input_html: {class: "form-control"}
    = f.input :reps, label: "# of Reps", input_html: {class: "form-control"}
    = f.input :progression, label: "Progression Level", input_html: {class: "form-control"}
    = f.input :example, label: "YouTube Embed Link", input_html: {class: "form-control"}
    %br 
    = f.button :submit

workout/app/views/workouts/categories.html.haml
%h2 All Categories Page
- @categories.each do |c|
    %div
        = link_to "#{c}s", category_path("#{c}")
        

workout/app/views/workouts/category.html.haml
= render './partials/category'

workout/app/views/workouts/edit.html.haml
%h1 Edit Workout

= render './partials/edit_form'

workout/app/views/workouts/home.html.haml
#main-content   
    .content-box    
        .content#one
            %h4 CORE
        .content#two
            %h4 POSTURE
        .content#three
            %h4 CARDIO
    .content-box  
        .content#four
            %h4 SIX PACK ABS
        .content#five
            %br
            %h1 RipFit
            %h3 The Mecca for Bodyweight Fitness
            .link
                %button{:onclick => "window.location.href= 'categories'"}
                    ENTER
        .content#six
            %h4 ASTHETICS
    .content-box  
        .content#seven
            %h4 STRENGTH
        .content#eight
            %h4 CONFIDENCE
        .content#nine
            %h4 NUTRITION

    

workout/app/views/workouts/index.html.haml
%h1 This is the Workouts#Index placeholder


.workouts
    - @workout.each do |w|
        .line
            %h2= link_to "#{w.name}", workout_path(w.id)
            %h4= link_to "#{w.category}", category_path(w.category) 
            %h6= "Reps: #{w.reps}"
            %p= "#{w.progression}"
        %br

workout/app/views/workouts/new.html.haml
%h1 New Workout
= render './partials/form'

workout/app/views/workouts/show.html.haml
%workout
    = @workout.name
    = @workout.category
    = @workout.reps
    = @workout.example
    = @workout.progression

.edit
    = link_to 'Edit', edit_workout_path(@workout) 
    = link_to 'Home', root_path 
    = link_to 'Delete', workout_path(@workout), method: :delete, data: {confirm: "Are you sure?"}